export const selectors = {
    homePage: {
        searchBox: '#text-search',
        searchButton: '#sp-btn-search',
        accountButton: 'a.dropdown-toggle[title="My Account"]',
        registerButton: '#pt-register-link',
        loginButton: '#pt-login-link',
        browseCategoriesButton: 'div[class="oc-menu-bar"]',
        categoryLink: 'a:has-text("{categoryName}")',
        subCategoryLink: 'a:has-text("{subCategoryName}")',
    },
    productPage: {
        listViewButton: '#list-view',
        productItem: '.product-item h4',
        productPrice: 'p[class="price"]',
        addToCartButton: '#button-cart',
        cartButton: '#cart',
        viewCartButton: '//p[@class="text-right"]/a[1]',
        filterOption: 'input[type="checkbox"][value="{{filterValue}}"]',
        sortingDropdown: 'select#input-sort',
        sortingOption: 'option[value="{sortingValue}"]',
        reviewTab: 'a[href="#tab-review"]',
        reviewNameInput: '#input-name',
        reviewTextInput: '#input-review',
        reviewRatingInput: 'input[name="rating"][value="{ratingValue}"]',
        reviewSubmitButton: '#button-review',
        reviewForm: 'form#form-review',
        reviewSuccessMessage: 'div.alert-success',
        approvedReview: '//td[@colspan="2"]/p[text()="This is an excellent product! Highly recommended."]',
    },
    cartPage: {
        cartItem: 'div[class="table-responsive"] tbody tr',
        checkoutButton: 'a[class="btn btn-primary"]',
        couponCodeInput: '#input-coupon',
        applyCouponButton: 'input[value="Apply Coupon"]',
        discountRow: 'tr:has-text("Discount")',
        couponCodeSection: 'div.panel-heading:has-text("Use Coupon Code")',
    },
    checkoutPage: {
        guestCheckoutRadio: 'input[value="guest"]',
        continueAccountButton: '#button-account',
        firstNameInput: '#input-payment-firstname',
        lastNameInput: '#input-payment-lastname',
        emailInput: '#input-payment-email',
        phoneInput: '#input-payment-telephone',
        addressInput: '#input-payment-address-1',
        cityInput: '#input-payment-city',
        postalCodeInput: '#input-payment-postcode',
        countrySelect: '#input-payment-country',
        regionSelect: '#input-payment-zone',
        continueBillingButton: '#button-guest',
        termAndConditionsCheckbox: 'input[name="agree"]',
        paymentMethodButton: '#button-payment-method',
        deliveryMethodButton: '#button-shipping-method',
        confirmOrderButton: '#button-confirm',
    },
    orderSuccessPage: {
        successMessage: '//div[@id="content"]/p[1]',
    },
    popup: {
        closeButton: '#popup2 > span > span',
    },
    registerPopup: {
        popupContainer: 'div[class="account-register"]',
        firstNameInput: '#input-firstname',
        lastNameInput: '#input-lastname',
        emailInput: '#input-register-email',
        phoneInput: '#input-telephone',
        passwordInput: '#input-register-password',
        confirmPasswordInput: '#input-confirm',
        privacyPolicyCheckbox: 'input[name="agree"]',
        submitButton: 'input.btn.btn-primary[value="Continue"]',
        successPopup: '//div[@class="account-success"]',
        continueButton: '(//button[@class="button" and span[text()="Continue"]])[1]',
    },
    loginPopup: {
        popupContainer: 'div[class="login-form-content"]',
        emailInput: '#input-login-email',
        passwordInput: '#input-login-password',
        submitButton: '#login-submit',
    },
    filtersPage: {
        categoryLink: 'a[href*="{categoryName}"]',
        categoryHeader: 'h1:has-text("{categoryName}")',
        filterDropdown: 'div.filter-dropdown[data-filter="{filterName}"]',
        filterOption: 'label:has-text("{filterOption}")',
        productItem: 'h4[class="product-name"]',
        sortingDropdown: 'select#input-sort',
        sortingOption: 'option[value="{sortingValue}"]',
    },
    adminPage: {
        loginUsernameInput: '#input-username',
        loginPasswordInput: '#input-password',
        loginButton: 'button[type="submit"]',
        navigationMenu: 'nav#menu',
        catalogMenu: 'a:has-text("Catalog")',
        reviewsMenu: 'a:has-text("Reviews")',
        reviewApproveButton: 'button[data-original-title="Approve"]',
        catalogDropdown: '#menu-catalog',
        reviewsLink: '//li/a[text()="Reviews"]',
        reviewEditButton: '//tr[td[text()="{authorName}"]]//td[@class="text-right"]/a[contains(@class, "btn-primary")]',

    },
    common: {
        addToCartButton: '#button-cart',
    }
};